-- AlterTable
ALTER TABLE "Chat" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updatedAt" DROP DEFAULT,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "ChatRoom" ALTER COLUMN "lastMessage" DROP NOT NULL,
ALTER COLUMN "lastChatRole" DROP NOT NULL;
